# Generated by Django 2.1 on 2020-05-14 23:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurseApp', '0008_auto_20200514_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='bp_diastolic',
            field=models.PositiveSmallIntegerField(default=80, help_text='Diastolic blood pressure. (lower #) - Normal: < 80', validators=[django.core.validators.MaxValueValidator(300)]),
        ),
        migrations.AlterField(
            model_name='record',
            name='bp_systolic',
            field=models.PositiveSmallIntegerField(default=120, help_text='Systolic blood pressure. (upper #) - Normal: < 120', validators=[django.core.validators.MaxValueValidator(300)]),
        ),
        migrations.AlterField(
            model_name='record',
            name='heart_rate',
            field=models.PositiveSmallIntegerField(default=60, help_text='Beats per minutes. (bpm) - Normal: 60 to 100 bmp at rest', validators=[django.core.validators.MaxValueValidator(300)]),
        ),
    ]
