# Generated by Django 2.1 on 2020-05-15 22:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurseApp', '0010_auto_20200514_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.PositiveSmallIntegerField(help_text="specify the patient's age.", validators=[django.core.validators.MaxValueValidator(150)], verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='custom_id',
            field=models.PositiveIntegerField(help_text='Later he/she will use it to access his/her historical data (e.g. ID Card number or Passport number)', unique=True, verbose_name='ID'),
        ),
    ]
