# Generated by Django 2.1 on 2020-05-15 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurseApp', '0012_auto_20200515_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='custom_id',
            field=models.SlugField(help_text='Later he/she will use it to access his/her historical data (e.g. ID Card number or Passport number)', unique=True, verbose_name='ID'),
        ),
    ]
