# Generated by Django 2.1 on 2020-05-14 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurseApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.PositiveSmallIntegerField(help_text='Specify how old is the patient.', verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='custom_id',
            field=models.PositiveSmallIntegerField(help_text='Add some Personal ID of the patient. (e.g. ID Card number or Passport number)', verbose_name="Patient's ID"),
        ),
    ]
