# Generated by Django 2.1 on 2020-05-14 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurseApp', '0002_auto_20200514_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='custom_id',
            field=models.PositiveSmallIntegerField(help_text='Later he/she will use it to see his/her historical data (e.g. ID Card number or Passport number)', verbose_name="Patient's ID"),
        ),
    ]
