# Generated by Django 2.1 on 2020-05-14 17:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurseApp', '0006_auto_20200514_1132'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_responsible', models.CharField(max_length=50)),
                ('id_patient', models.CharField(max_length=50)),
                ('bp_systolic', models.PositiveSmallIntegerField(default='120', help_text='Systolic blood pressure. (upper #) - Normal: < 120', validators=[django.core.validators.MaxValueValidator(300)])),
                ('bp_diastolic', models.PositiveSmallIntegerField(default='80', help_text='Diastolic blood pressure. (lower #) - Normal: < 80', validators=[django.core.validators.MaxValueValidator(300)])),
                ('heart_rate', models.PositiveSmallIntegerField(default='60', help_text='Beats per minutes. (bpm) - Normal: 60 to 100 bmp at rest', validators=[django.core.validators.MaxValueValidator(300)])),
                ('ts', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='patient',
            name='records',
        ),
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.PositiveSmallIntegerField(help_text='Specify how old is the patient.', validators=[django.core.validators.MaxValueValidator(150)], verbose_name='Age'),
        ),
    ]
