# Generated by Django 2.1 on 2020-05-14 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurseApp', '0007_auto_20200514_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='id_patient',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='record',
            name='id_responsible',
            field=models.CharField(default='', max_length=50),
        ),
    ]
