# Generated by Django 2.1 on 2020-05-16 00:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurseApp', '0013_auto_20200515_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='custom_id',
            field=models.CharField(help_text='Later he/she will use it to access his/her historical data (e.g. ID Card number or Passport number)', max_length=20, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')], verbose_name='ID'),
        ),
    ]
